### PR TITLE
Solved issue 1

### PR DESCRIPTION
**Pull request by tanya-vedi**
https://github.com/scriptnull/oss-checklist/issues/10

### CODE REVIEW

**Comment by scriptnull** [comment]
Hi @tanya-vedi,

Thanks for the PR. The CI Seems to be failing ( https://semaphoreci.com/scriptnull/oss-checklist/branches/pull-request-13/builds/1 ) as [mdspell](https://www.npmjs.com/package/markdown-spellcheck) is reporting the names of the CI services as wrong spellings. 

Since we know that they are valid terms, we could add them to [.spelling file](https://github.com/scriptnull/oss-checklist/blob/master/.spelling) to ignore them, while checking.

So, could you please make a commit with the red colored words ( in below image ) added to the `.spelling` file ?

image

**Comment by tanya-vedi** [comment]
Ya sure

**Comment by scriptnull** [comment]
@tanya-vedi I merged both the PRs and here are some small tips.

1. It's always good to reference the issue your working on, by explicitly using the issue link in your PR description. This will enable other people looking at the issue to know that, an active PR is raised for the current issue and avoid multiple people working on the same issue. ( Example: after I edited our PR descriptions, the issue looks like below )
image

2. If there are any PR suggestions, you could always make an incremental commit and push to the same branch your PR was raised from ( In this case `patch-3` ). This will update the PR automatically and CI will run on the contents of PR once again and this would ease the reader by seeing all the changes related to a PR at one single place.

Anyways, thanks for the effort and taking time to make the checklist better 👍

**Comment by tanya-vedi** [comment]
Thanks for your valuable advice @scriptnull. Much appreciated.

**Pull request merged**
